version: "3.6"

services:
  web:
    build: ./web/
    ports:
      - "3000:3000"
      - "8081:8080"
    volumes:
      - ./web:/app
    command: yarn run dev
    environment:
      - NODE_ENV="development"
